### ISSUE TITLE
cwd changes to .git when nvim is used to edit commit messages

### ISSUE THREAD

**Issue by astier** [airblade/vim-rooter#110] opened 2020-07-11 18:29 UTC
Hello. I use `nvim v0.4.3`. When nvim opens a git-commit-message rooter changes the cwd to `.git` directory because the file for the commit-message is stored there. I think it should stay in the actual root-dir, namely the dir above .git. Or is it somehow possible to ignore certain files?

**Comment by airblade** [comment] 2020-07-14 09:53
What is your `g:rooter_patterns`?

**Comment by astier** [comment] 2020-07-14 18:08
### General Info

- `nvim v0.4.3`
- `let g:rooter_patterns = ['.git', '.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']`

### Minimal init.vim

```vim
cal plug#begin('~/.local/share/nvim/plugins')
Plug 'airblade/vim-rooter'
cal plug#end()
```

### Steps to reproduce

```sh
mkdir repo
cd repo
git init
nvim .git/config
:pw<cr>
```
### Actual behavior

The vim command `pw` shows that the current cwd is `.git`.

### Expected behavior

The new cwd should be `repo`.

**Comment by airblade** [comment] 2020-07-15 09:16
Try `let g:rooter_patterns = ['.git/']`.

**Comment by astier** [comment] 2020-07-15 10:08
It still happens. I also tried it with vim 8.2. With bash and dash. With the xterm- and st-terminal. You can not reproduce it?

**Comment by astier** [comment] 2020-07-15 10:52
I tried it right now also on an Ubuntu Live-USB Stick. I used vim, bash and the gnome terminal.

**Comment by airblade** [comment] 2020-07-15 11:54
I can reproduce it now; I'm not sure why I couldn't before.

I agree that the root directory in this case should be the directory above `.git/`.  However this has never bothered me because after writing the commit message, vim/nvim closes (because I am on the command line).

Does this actually cause you any inconvenience?

**Comment by astier** [comment] 2020-07-15 12:51
> Does this actually cause you any inconvenience?

Yes, because of my vim/terminal-workflow. Instead of the default shell my terminal opens nvim in terminal-mode. This means I'm always inside vim when I use a terminal. I never really leave vim. In order not to open nested vim-sessions I use [neovim-remote](https://github.com/mhinz/neovim-remote). Whenever I open from the terminal a file its opened in the current vim-session which also runs the terminal-buffer. This also goes for commit-messages. The problem is now that whenever I open a commit-message my cwd changes to `.git` for the whole vim-session. This brings a bunch of problems with it.

So far I am working with the solution which I posted in my PR. It works for me and I had no issues. However, I am only working with git repositories and didn't test it with other patterns. I also didn't test it with vim (only nvim).

What do you think about my PR? First of all it fixes this issue, at least for me it worked so far. Second, it simplifies the code greatly. Of course I don't want to break anything and there might be corner-cases which I didn't think about which you are currently solving with the current code.

**Comment by airblade** [comment] 2020-07-15 13:14
Thanks for the clarification.

I’m away at the moment but will look at the PR once I’m back in a few days.

**Comment by airblade** [comment] 2020-07-15 16:07
The problem here is a conflict between two of the three ways the plugin identifies a root directory:

- a root directory contains a specific directory, e.g. a git repo's top-level directory has a `.git/` directory;
- a root directory being a known directory.

A file below `.git/` matches both of the above conditions.  The second criterion "wins" but the first should.

**Comment by astier** [comment] 2020-07-15 23:51
By removing the pattern from the end of the match the whole logic becomes much more simpler. Then there are only two possible cases:

1. The match becomes empty --> We are in the right directory. Return empty string.
2. The match is non empty --> We need to change the directory to match. Return absolute path of match.

**Comment by airblade** [comment] 2020-07-20 08:41
This is fixed in 9b1fc7a.

**Closed by airblade** 2020-07-20 08:41 UTC

**Comment by astier** [comment] 2020-07-20 10:15
Thank you. Didn't think this would trigger such a huge commit.

**Comment by airblade** [comment] 2020-07-20 10:23
I had several pent-up changes I wanted to make and they all came out at once...

**Comment by airblade** [comment] 2021-06-08 11:39
Hi @weilbith, please could you draw me a little ASCII tree of the various directories involved?  I'm not confident I fully understand your setup.

**Comment by weilbith** [comment] 2021-06-08 12:04
Sure. :)

Following the instructions I wrote [here](https://github.com/TimUntersberger/neogit/issues/90#issuecomment-850885392) you get the following:

```
/tmp/tmp.<something>/
   |- project-main/
   |     |- .git/
   |     L bar.txt
   L project-prs/
         |- .git/
         |- bar.txt
         L foo.txt
```

Note hat both `project-*` directories are worktrees of the same Git repository. But only `project-main/.git` includes the actual Git database, where `project-prs/.git` is a plain file which includes `gitdir: /tmp/tmp.<something>/project-main/.git/worktrees/project-prs`. That's just how Git worktrees work. Anyway.
Vim gets opened to edit `/tmp/tmp.<something>/project-prs/foo.txt`. Due to the entry of `.git/` in `g:rooter_patterns`, `vim-root` correctly sets the working directory to `/tmp/tmp.<something>/project-prs`. Now if you do a Bit commit with the plugin NeoGit it opens a file inside the main worktree, to be exact it is `/tmp/tmp.<something>/project-main/.git/worktrees/project-prs/NEOGIT_COMMIT_EDITMSG`. If I now check `:pwd` in this buffer, it tells me to be `/tmp/tmp.<something>/project-main`. This causes an issue, because if `NeoGit` now tries to execute the Git commit command, it runs in the wrong directory (should be `/tmp/tmp.<something>/project-prs`).

Alright. Sorry that is a lot of overhead. In fact `vim-rooter` works as expected. But I need to make an exception here. So if a buffer is called `NEOGIT_COMMIT_EDITMSG`, it should not automatically change the directory.

PS:
The above example with `NeoGit` works if I put `vim-rooter` into the manual mode.

**Comment by airblade** [comment] 2021-06-08 12:18
Thanks for spelling it all out.  I appreciate it :)

This solves the problem for me:

```vim
let g:rooter_patterns=["!.git/**/NEOGIT_COMMIT_EDITMSG", ".git"]
```

Does it work for you?

**Comment by weilbith** [comment] 2021-06-08 12:59
It actually does! Thank you very much! 🙏🏾 

I made it more generic an used `!.git/worktrees/*`. I tried `!=.git/worktrees` before, but that didn't work. Does the order actually matter here? 🤔

**Comment by airblade** [comment] 2021-06-08 13:16
It's a [breadth-first search](https://github.com/airblade/vim-rooter/blob/662c00676abab9d7ce16bf9f202420bf86cc6554/plugin/rooter.vim#L121-L139):

- Set the directory being considered to the current working directory.
- Consider each pattern in turn.
  - If a non-exclusionary pattern matches, the current directory is the root directory and the search exits.
  - If an exclusionary (`!`) pattern matches, no further patterns are considered for the current directory.
- Set the directory being considered to the parent of the directory we have just considered and start again.

So you want to specify exclusionary patterns before any other patterns.

The reason `!=.git/worktrees` doesn't work is that [`=` compares a directory name](https://github.com/airblade/vim-rooter/blob/662c00676abab9d7ce16bf9f202420bf86cc6554/plugin/rooter.vim#L164) rather than a path or glob.  You would have to use either `!=worktrees` or `!=.git` but neither does what you want.

I like your generalisation to `!.git/worktrees/*`.  That's a better solution than mine.  In fact you could use simply `!.git/worktrees`.
