### ISSUE TITLE
Opening files in existing gvim does not change root

### ISSUE THREAD

**Issue by MartinWallgren** [airblade/vim-rooter#99] opened 2019-11-01 10:43 UTC
With a running gvim instance you can open files in the existing instance with:

`gvim --remote-silent /some/path/to/file`

But this does not trigger vim-rooter to change directory.

Opening files from within gvim triggers vim-rooter as expected (i.e the plugin is installed and configured as expected).

I'm using vim 8.1 on Linux and the commit for vim+rooter is eef98131.

**Comment by airblade** [comment] 2020-07-20 09:05
Fixed by e35b4a0.

**Closed by airblade** 2020-07-20 09:05 UTC

**Comment by vds2212** [comment] 2021-07-15 17:46
Dear vim-rooter,

I'm having the same problem on Windows 10 with vim 8.2 (2019 Dec 12)
But also with a more recent version vim 8.2 (2021 Jan 29 including patch 1-2425)

I use the last version of vim-rooter (9a5ce8e 2021 Jun 8)

Let me know how I can help solving the problem.

Best regards,
Vivian.

**Comment by airblade** [comment] 2021-09-09 13:25
@vds2212 I'm sorry, I can't reproduce the problem; it works for me.  I'm on MacVim 8.2.3008 and vim-rooter 9a5ce8e.

**Comment by vds2212** [comment] 2021-09-11 05:14
Thanks for your help. I'll try by myself. I'll keep you posted.
