### ISSUE TITLE
Rooter breaks Vim diff mode

### ISSUE THREAD

**Issue by niboan** [airblade/vim-rooter#75] opened 2018-05-17 12:00 UTC
When running Vim diff on files in subdirectories of a rooted directory, the second file is not opened correctly.

To reproduce, create the directory structure
```
dir
  '- subdir
      |- file1.txt
      '- file2.txt
```
When running `vim -d file1.txt file2.txt` from `subdir`, everything works as expected.

Now, create a `.git` directory in `dir`, to make this the root:
```
dir
  |- .git
  '- subdir
      |- file1.txt
      '- file2.txt
```
When running the same command again, the second window will be empty, and Vim says
```
"subdir\file2.txt" [New DIRECTORY]
```
It seems the second file is opened as `dir/subdir/subdir/file2.txt` instead of `dir/subdir/file2.txt`.

Running `vim -d subdir\file1.txt subdir\file2.txt` from `dir` works, but running from everywhere else, even with absolute file paths, won't work.

**Comment by niboan** [comment] 2018-05-18 06:41
No, 3509dfb has the same problem.

**Comment by niboan** [comment] 2018-05-22 07:33
Yes, this is on Windows, and I'm running on a clean profile, only plugin is vim-rooter.
It wouldn't be the first escaping problem I've run into on Windows ;-)
I haven't tried on Linux, but I can do that later.

**Comment by airblade** [comment] 2019-02-25 09:23
Closing because it's gone quiet.

**Closed by airblade** 2019-02-25 09:23 UTC

**Comment by pseewald** [comment] 2021-03-11 10:45
I‘m having the same issue (on Windows) and I confirm that it‘s specific for Windows as I can not reproduce it on Linux. I‘ll have a closer look...

**Comment by airblade** [comment] 2021-03-11 11:00
@pseewald Thank you.

**Comment by pseewald** [comment] 2021-03-11 13:48
Just to illustrate what is wrong, let‘s assume we have two files in `root/dir/file1` and `root/dir/file2`, with vim-rooter enabled:

As expected:
```
cd dir; vim file1
:pwd
root
:file 
dir/file1
```

Wrong path when opening 2 windows:
```
cd dir; vim -o file1 file2
:pwd
root/dir
:file 
dir/file1
1Ctrl-g (to show full path)
root/dir/file1
Ctrl-wj (to switch to file2)
1Ctrl-g (to show full path)
root/dir/dir/file2
```

I have no idea what‘s going on but it seems that changing the working directory at an early stage as vim-rooter does (after `BufReadPost`) conflicts with the vim mechanism of opening multiple windows (which seems to work differently on Windows than on other systems). I don‘t think it‘s an escaping problem.

Proposed solution: restrict the vim-rooter autocommand for changing the working directory to `VimEnter` (so dropping `BufReadPost, BufEnter`). Would that be possible?

**Comment by airblade** [comment] 2021-03-11 13:59
Thanks for investigating.  I agree, it doesn't seem like an escaping problem.  It looks to me like a bug in vim.

Re your proposed solution, you can of course add and remove autocommands in your vimrc.  Personally I want vim-rooter to run every time I switch to a buffer because I often have files from different "roots" open and want vim to use the appropriate root when searching, navigating, etc.

**Comment by pseewald** [comment] 2021-03-11 14:59
Yes this is probably a bug in Vim for Windows and we should not try to fix this within vim-rooter.

However it‘s not possible to remove autocommands defined by plugins in vimrc (since plugins are loaded after vimrc). The workaround needs to be as follows (I leave this here just for documentation):

Create a file `$HOME/vimfiles/after/plugin/rooter.vim` with the content
```vim
augroup rooter
  autocmd!
  autocmd VimEnter * nested if !g:rooter_manual_only | Rooter | endif
  autocmd BufWritePost * nested if !g:rooter_manual_only | call setbufvar('%', 'rootDir', '') | Rooter | endif
augroup END
```

**Comment by niboan** [comment] 2021-03-12 11:49
The reason I haven't looked into the problem further, is that I switched to using `lcd`, because it worked better with some of my other plugins.
That made the problem go away, so that's also a workaround, unless you depend on using `cd`.

**Comment by airblade** [comment] 2021-03-12 11:55
@pseewald Or even simpler:

```vim
autocmd! rooter BufEnter,BufRead
```

@niboan That's good to know, thanks.  `let g:rooter_cd_cmd = 'lcd'`
