### ISSUE TITLE
conflicts with vim-fugitive

### ISSUE THREAD

**Issue by mcepl** [airblade/vim-rooter#60] opened 2017-02-07 14:17 UTC
This plugin seems to be in conflict with [vim-fugitive](https://github.com/tpope/vim-fugitive/). When I open a document, and then other document with ``tabedit some-long-path-somewhere-complete-else``, your plugin switched lcd, but then when I edit the new file, and run ``:Gwrite`` I get
```
fugitive: cannot determine file path 
```

**Comment by airblade** [comment] 2017-02-07 23:06
My first hypothesis would be that fugitive has some kind of BufRead autocommand which caches the relative file path, and which fires before vim-rooter's does.  Then when you `:Gwrite` vim-fugitive finds out the path doesn't make sense any more.

**Comment by mcepl** [comment] 2017-02-08 00:36
That should be translated into "file a bug with them"? Would just mentioning of @tpope help?

**Comment by airblade** [comment] 2017-02-08 09:49
I can't reproduce this:

```sh
$ mkdir foo bar
$ cd foo && touch foo.txt && git init && git add . && git commit -m "asdf" && cd -
$ cd bar && touch bar.txt && git init && git add . && git commit -m "asdf" && cd -
$ cd foo && vim --cmd "let g:rooter_use_lcd=1" foo.txt
```

Inside vim:

```viml
:tabedit ../bar/bar.txt
iblah<ESC>
:Gwrite
```

Expected: `bar.txt` is saved and committed.
Actual: as expected.

**Comment by airblade** [comment] 2017-04-25 14:05
I can't reproduce this and it's gone quiet so I'm going to close it.  If it's still a problem then we can discuss it further.

**Closed by airblade** 2017-04-25 14:05 UTC

**Comment by mcepl** [comment] 2017-04-25 15:28
Well, this has gone quiet because I uninstalled vim-rooter, of course.

**Comment by mcepl** [comment] 2017-04-25 15:45
Yeah, this has not been fixed and can be easily reproduced for me.
```
$ cd ~/rhprojekty/libgxps/
$ vim testmapper.txt
# and inside of vim
:tabedit ~/Dokumenty/clanky/petunia_dursley/kampa.rst
" write, write, write
:Gwrite
```
and I get nice ``"fugitive: cannot determine file path"`` error. Perhaps it helps, that all those paths are heavily symlinked (so ``~/Dokumenty`` is a symlink to ``~/archiv/2017`` and ``~/rhprojekty`` is a symlink to (already symlinked) ``~/Dokumenty/RedHat/projekty``). In both tabs, ``:pwd`` gives me full all-symlinks-exploded path (e.g., ``/home/matej/archiv/2017/RedHat/projekty/libgxps`` and ``/home/matej/archiv/2016/clanky/petunia_dursley`` respectively, which probably shouldn’t be The Wrong Thing™, should it?).

**Comment by tpope** [comment] 2017-04-25 16:55
Vim's symlink handling is kind of wonky. I'm not sure how it interacts with `cd`, exactly, but if changing the directory causes the buffer to be renamed, it could definitely confuse Fugitive. You should check `:echo expand('%:p')` and `:echo b:git_dir` and make sure they correspond.

I can't vouch for it myself, but [here's a workaround](https://github.com/tpope/vim-fugitive/issues/895#issuecomment-293836447) other people with symlink woes seem find helpful.

**Comment by airblade** [comment] 2017-04-25 18:39
@mcepl I tried to reproduce your symlink arrangement but I just wasn't able to break Rooter or Fugitive.  I'm using the latest commit of both and vim 8.0.525.

> In both tabs, :pwd gives me full all-symlinks-exploded path (e.g., /home/matej/archiv/2017/RedHat/projekty/libgxps and /home/matej/archiv/2016/clanky/petunia_dursley respectively

So Rooter is changing the current working directory as expected.  I don't know why that might interact poorly with Fugitive.

**Comment by mcepl** [comment] 2017-04-25 21:04
> Vim's symlink handling is kind of wonky. I'm not sure how it interacts with cd, exactly, but if changing the directory causes the buffer to be renamed, it could definitely confuse Fugitive. You should check :echo expand('%:p') and :echo b:git_dir and make sure they correspond.

1. first file:
    ``expand('%:p')`` /home/matej/archiv/2017/RedHat/projekty/libgxps/testmapper.txt
    ``b:git_dir`` /home/matej/archiv/2017/RedHat/projekty/libgxps/.git

2. second file:
    ``b:git_dir`` /home/matej/Dokumenty/clanky/petunia_dursley/.git
    ``expand('%:p')`` /home/matej/archiv/2016/clanky/petunia_dursley/kampa.rst

(that’s without the workaround from https://github.com/tpope/vim-fugitive/issues/895#issuecomment-293836447)

OK, this doesn’t make any sense. Why ``b:git_dir`` is expanded for the first file, but not for the second one?

> I can't vouch for it myself, but here's a workaround other people with symlink woes seem find helpful.

OK, adding that line to my ``~/.vimrc`` leads to even worse problems. When trying to reproduce the steps described [above](https://github.com/airblade/vim-rooter/issues/60#issuecomment-297073627) then with opened second document, when I try plain ``:w`` I get error:
```
E13: File exists (add ! to override)
```
I would say that makes things worse.

**Comment by airblade** [comment] 2017-04-26 08:05
@mcepl FYI the `g:rooter_resolve_links` setting tells Rooter [whether or not to follow the link](https://github.com/airblade/vim-rooter/blob/aaac40828cf6fcd27d56e00c005e29a8a5ee0fb1/plugin/rooter.vim#L126-L128) before it starts looking for the buffer's "root" directory.

By default it is off.

**Comment by mcepl** [comment] 2017-04-26 09:21
1. ``g:rooter_resolve_links`` doesn’t seem to make any difference

2. Actually, ``:Gwrite`` works in the first tab with the expanded ``b:git_dir`` variable. So, I tried to just
    ```
    let b:git_dir="/home/matej/archiv/2016/clanky/petunia_dursley/.git"
    ```
    in the second tab and then ``:Gwrite`` starts to work.

**Comment by tpope** [comment] 2017-04-27 23:41
https://github.com/tpope/vim-fugitive/issues/831 looks very relevant.
